version: '3'

networks:
  default:
    driver: bridge

services:
  web:
    image: nginx:latest
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/html"
    ports:
      - 8080:80
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - pgsql

  composer:
    image: composer
    volumes:
      - "./app:/app"
    command: install
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php.docker
    volumes:
      - "./app:/var/www/html"
    depends_on:
      - pgsql

  pgsql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=wiam
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
    ports:
      - 5556:5432